/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.alone.thrift.struct;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2016-08-04")
public class AppPackageStruct implements org.apache.thrift.TBase<AppPackageStruct, AppPackageStruct._Fields>, java.io.Serializable, Cloneable, Comparable<AppPackageStruct> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("AppPackageStruct");

  private static final org.apache.thrift.protocol.TField ID_FIELD_DESC = new org.apache.thrift.protocol.TField("id", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("name", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField COMMON_FIELD_DESC = new org.apache.thrift.protocol.TField("common", org.apache.thrift.protocol.TType.BOOL, (short)3);
  private static final org.apache.thrift.protocol.TField ROOT_FIELD_DESC = new org.apache.thrift.protocol.TField("root", org.apache.thrift.protocol.TType.BOOL, (short)4);
  private static final org.apache.thrift.protocol.TField BRAND_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("brand_id", org.apache.thrift.protocol.TType.I64, (short)5);
  private static final org.apache.thrift.protocol.TField MODEL_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("model_id", org.apache.thrift.protocol.TType.I64, (short)6);
  private static final org.apache.thrift.protocol.TField VERSION_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("version_id", org.apache.thrift.protocol.TType.I64, (short)7);
  private static final org.apache.thrift.protocol.TField BASE_VERSION_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("base_version_id", org.apache.thrift.protocol.TType.I64, (short)8);
  private static final org.apache.thrift.protocol.TField PACKAGE_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("package_id", org.apache.thrift.protocol.TType.I64, (short)9);
  private static final org.apache.thrift.protocol.TField PRE_FIELD_DESC = new org.apache.thrift.protocol.TField("pre", org.apache.thrift.protocol.TType.LIST, (short)10);
  private static final org.apache.thrift.protocol.TField INSTALL_FIELD_DESC = new org.apache.thrift.protocol.TField("install", org.apache.thrift.protocol.TType.LIST, (short)11);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new AppPackageStructStandardSchemeFactory());
    schemes.put(TupleScheme.class, new AppPackageStructTupleSchemeFactory());
  }

  private long id; // required
  private String name; // required
  private boolean common; // required
  private boolean root; // required
  private long brand_id; // optional
  private long model_id; // optional
  private long version_id; // optional
  private long base_version_id; // optional
  private long package_id; // required
  private List<Long> pre; // optional
  private List<Long> install; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ID((short)1, "id"),
    NAME((short)2, "name"),
    COMMON((short)3, "common"),
    ROOT((short)4, "root"),
    BRAND_ID((short)5, "brand_id"),
    MODEL_ID((short)6, "model_id"),
    VERSION_ID((short)7, "version_id"),
    BASE_VERSION_ID((short)8, "base_version_id"),
    PACKAGE_ID((short)9, "package_id"),
    PRE((short)10, "pre"),
    INSTALL((short)11, "install");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ID
          return ID;
        case 2: // NAME
          return NAME;
        case 3: // COMMON
          return COMMON;
        case 4: // ROOT
          return ROOT;
        case 5: // BRAND_ID
          return BRAND_ID;
        case 6: // MODEL_ID
          return MODEL_ID;
        case 7: // VERSION_ID
          return VERSION_ID;
        case 8: // BASE_VERSION_ID
          return BASE_VERSION_ID;
        case 9: // PACKAGE_ID
          return PACKAGE_ID;
        case 10: // PRE
          return PRE;
        case 11: // INSTALL
          return INSTALL;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ID_ISSET_ID = 0;
  private static final int __COMMON_ISSET_ID = 1;
  private static final int __ROOT_ISSET_ID = 2;
  private static final int __BRAND_ID_ISSET_ID = 3;
  private static final int __MODEL_ID_ISSET_ID = 4;
  private static final int __VERSION_ID_ISSET_ID = 5;
  private static final int __BASE_VERSION_ID_ISSET_ID = 6;
  private static final int __PACKAGE_ID_ISSET_ID = 7;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.BRAND_ID,_Fields.MODEL_ID,_Fields.VERSION_ID,_Fields.BASE_VERSION_ID,_Fields.PRE,_Fields.INSTALL};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ID, new org.apache.thrift.meta_data.FieldMetaData("id", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.NAME, new org.apache.thrift.meta_data.FieldMetaData("name", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.COMMON, new org.apache.thrift.meta_data.FieldMetaData("common", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.ROOT, new org.apache.thrift.meta_data.FieldMetaData("root", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.BRAND_ID, new org.apache.thrift.meta_data.FieldMetaData("brand_id", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.MODEL_ID, new org.apache.thrift.meta_data.FieldMetaData("model_id", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.VERSION_ID, new org.apache.thrift.meta_data.FieldMetaData("version_id", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.BASE_VERSION_ID, new org.apache.thrift.meta_data.FieldMetaData("base_version_id", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.PACKAGE_ID, new org.apache.thrift.meta_data.FieldMetaData("package_id", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.PRE, new org.apache.thrift.meta_data.FieldMetaData("pre", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64))));
    tmpMap.put(_Fields.INSTALL, new org.apache.thrift.meta_data.FieldMetaData("install", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(AppPackageStruct.class, metaDataMap);
  }

  public AppPackageStruct() {
  }

  public AppPackageStruct(
    long id,
    String name,
    boolean common,
    boolean root,
    long package_id)
  {
    this();
    this.id = id;
    setIdIsSet(true);
    this.name = name;
    this.common = common;
    setCommonIsSet(true);
    this.root = root;
    setRootIsSet(true);
    this.package_id = package_id;
    setPackage_idIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public AppPackageStruct(AppPackageStruct other) {
    __isset_bitfield = other.__isset_bitfield;
    this.id = other.id;
    if (other.isSetName()) {
      this.name = other.name;
    }
    this.common = other.common;
    this.root = other.root;
    this.brand_id = other.brand_id;
    this.model_id = other.model_id;
    this.version_id = other.version_id;
    this.base_version_id = other.base_version_id;
    this.package_id = other.package_id;
    if (other.isSetPre()) {
      List<Long> __this__pre = new ArrayList<Long>(other.pre);
      this.pre = __this__pre;
    }
    if (other.isSetInstall()) {
      List<Long> __this__install = new ArrayList<Long>(other.install);
      this.install = __this__install;
    }
  }

  public AppPackageStruct deepCopy() {
    return new AppPackageStruct(this);
  }

  @Override
  public void clear() {
    setIdIsSet(false);
    this.id = 0;
    this.name = null;
    setCommonIsSet(false);
    this.common = false;
    setRootIsSet(false);
    this.root = false;
    setBrand_idIsSet(false);
    this.brand_id = 0;
    setModel_idIsSet(false);
    this.model_id = 0;
    setVersion_idIsSet(false);
    this.version_id = 0;
    setBase_version_idIsSet(false);
    this.base_version_id = 0;
    setPackage_idIsSet(false);
    this.package_id = 0;
    this.pre = null;
    this.install = null;
  }

  public long getId() {
    return this.id;
  }

  public AppPackageStruct setId(long id) {
    this.id = id;
    setIdIsSet(true);
    return this;
  }

  public void unsetId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ID_ISSET_ID);
  }

  /** Returns true if field id is set (has been assigned a value) and false otherwise */
  public boolean isSetId() {
    return EncodingUtils.testBit(__isset_bitfield, __ID_ISSET_ID);
  }

  public void setIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ID_ISSET_ID, value);
  }

  public String getName() {
    return this.name;
  }

  public AppPackageStruct setName(String name) {
    this.name = name;
    return this;
  }

  public void unsetName() {
    this.name = null;
  }

  /** Returns true if field name is set (has been assigned a value) and false otherwise */
  public boolean isSetName() {
    return this.name != null;
  }

  public void setNameIsSet(boolean value) {
    if (!value) {
      this.name = null;
    }
  }

  public boolean isCommon() {
    return this.common;
  }

  public AppPackageStruct setCommon(boolean common) {
    this.common = common;
    setCommonIsSet(true);
    return this;
  }

  public void unsetCommon() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __COMMON_ISSET_ID);
  }

  /** Returns true if field common is set (has been assigned a value) and false otherwise */
  public boolean isSetCommon() {
    return EncodingUtils.testBit(__isset_bitfield, __COMMON_ISSET_ID);
  }

  public void setCommonIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __COMMON_ISSET_ID, value);
  }

  public boolean isRoot() {
    return this.root;
  }

  public AppPackageStruct setRoot(boolean root) {
    this.root = root;
    setRootIsSet(true);
    return this;
  }

  public void unsetRoot() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ROOT_ISSET_ID);
  }

  /** Returns true if field root is set (has been assigned a value) and false otherwise */
  public boolean isSetRoot() {
    return EncodingUtils.testBit(__isset_bitfield, __ROOT_ISSET_ID);
  }

  public void setRootIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ROOT_ISSET_ID, value);
  }

  public long getBrand_id() {
    return this.brand_id;
  }

  public AppPackageStruct setBrand_id(long brand_id) {
    this.brand_id = brand_id;
    setBrand_idIsSet(true);
    return this;
  }

  public void unsetBrand_id() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __BRAND_ID_ISSET_ID);
  }

  /** Returns true if field brand_id is set (has been assigned a value) and false otherwise */
  public boolean isSetBrand_id() {
    return EncodingUtils.testBit(__isset_bitfield, __BRAND_ID_ISSET_ID);
  }

  public void setBrand_idIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __BRAND_ID_ISSET_ID, value);
  }

  public long getModel_id() {
    return this.model_id;
  }

  public AppPackageStruct setModel_id(long model_id) {
    this.model_id = model_id;
    setModel_idIsSet(true);
    return this;
  }

  public void unsetModel_id() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __MODEL_ID_ISSET_ID);
  }

  /** Returns true if field model_id is set (has been assigned a value) and false otherwise */
  public boolean isSetModel_id() {
    return EncodingUtils.testBit(__isset_bitfield, __MODEL_ID_ISSET_ID);
  }

  public void setModel_idIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __MODEL_ID_ISSET_ID, value);
  }

  public long getVersion_id() {
    return this.version_id;
  }

  public AppPackageStruct setVersion_id(long version_id) {
    this.version_id = version_id;
    setVersion_idIsSet(true);
    return this;
  }

  public void unsetVersion_id() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __VERSION_ID_ISSET_ID);
  }

  /** Returns true if field version_id is set (has been assigned a value) and false otherwise */
  public boolean isSetVersion_id() {
    return EncodingUtils.testBit(__isset_bitfield, __VERSION_ID_ISSET_ID);
  }

  public void setVersion_idIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __VERSION_ID_ISSET_ID, value);
  }

  public long getBase_version_id() {
    return this.base_version_id;
  }

  public AppPackageStruct setBase_version_id(long base_version_id) {
    this.base_version_id = base_version_id;
    setBase_version_idIsSet(true);
    return this;
  }

  public void unsetBase_version_id() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __BASE_VERSION_ID_ISSET_ID);
  }

  /** Returns true if field base_version_id is set (has been assigned a value) and false otherwise */
  public boolean isSetBase_version_id() {
    return EncodingUtils.testBit(__isset_bitfield, __BASE_VERSION_ID_ISSET_ID);
  }

  public void setBase_version_idIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __BASE_VERSION_ID_ISSET_ID, value);
  }

  public long getPackage_id() {
    return this.package_id;
  }

  public AppPackageStruct setPackage_id(long package_id) {
    this.package_id = package_id;
    setPackage_idIsSet(true);
    return this;
  }

  public void unsetPackage_id() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __PACKAGE_ID_ISSET_ID);
  }

  /** Returns true if field package_id is set (has been assigned a value) and false otherwise */
  public boolean isSetPackage_id() {
    return EncodingUtils.testBit(__isset_bitfield, __PACKAGE_ID_ISSET_ID);
  }

  public void setPackage_idIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __PACKAGE_ID_ISSET_ID, value);
  }

  public int getPreSize() {
    return (this.pre == null) ? 0 : this.pre.size();
  }

  public java.util.Iterator<Long> getPreIterator() {
    return (this.pre == null) ? null : this.pre.iterator();
  }

  public void addToPre(long elem) {
    if (this.pre == null) {
      this.pre = new ArrayList<Long>();
    }
    this.pre.add(elem);
  }

  public List<Long> getPre() {
    return this.pre;
  }

  public AppPackageStruct setPre(List<Long> pre) {
    this.pre = pre;
    return this;
  }

  public void unsetPre() {
    this.pre = null;
  }

  /** Returns true if field pre is set (has been assigned a value) and false otherwise */
  public boolean isSetPre() {
    return this.pre != null;
  }

  public void setPreIsSet(boolean value) {
    if (!value) {
      this.pre = null;
    }
  }

  public int getInstallSize() {
    return (this.install == null) ? 0 : this.install.size();
  }

  public java.util.Iterator<Long> getInstallIterator() {
    return (this.install == null) ? null : this.install.iterator();
  }

  public void addToInstall(long elem) {
    if (this.install == null) {
      this.install = new ArrayList<Long>();
    }
    this.install.add(elem);
  }

  public List<Long> getInstall() {
    return this.install;
  }

  public AppPackageStruct setInstall(List<Long> install) {
    this.install = install;
    return this;
  }

  public void unsetInstall() {
    this.install = null;
  }

  /** Returns true if field install is set (has been assigned a value) and false otherwise */
  public boolean isSetInstall() {
    return this.install != null;
  }

  public void setInstallIsSet(boolean value) {
    if (!value) {
      this.install = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ID:
      if (value == null) {
        unsetId();
      } else {
        setId((Long)value);
      }
      break;

    case NAME:
      if (value == null) {
        unsetName();
      } else {
        setName((String)value);
      }
      break;

    case COMMON:
      if (value == null) {
        unsetCommon();
      } else {
        setCommon((Boolean)value);
      }
      break;

    case ROOT:
      if (value == null) {
        unsetRoot();
      } else {
        setRoot((Boolean)value);
      }
      break;

    case BRAND_ID:
      if (value == null) {
        unsetBrand_id();
      } else {
        setBrand_id((Long)value);
      }
      break;

    case MODEL_ID:
      if (value == null) {
        unsetModel_id();
      } else {
        setModel_id((Long)value);
      }
      break;

    case VERSION_ID:
      if (value == null) {
        unsetVersion_id();
      } else {
        setVersion_id((Long)value);
      }
      break;

    case BASE_VERSION_ID:
      if (value == null) {
        unsetBase_version_id();
      } else {
        setBase_version_id((Long)value);
      }
      break;

    case PACKAGE_ID:
      if (value == null) {
        unsetPackage_id();
      } else {
        setPackage_id((Long)value);
      }
      break;

    case PRE:
      if (value == null) {
        unsetPre();
      } else {
        setPre((List<Long>)value);
      }
      break;

    case INSTALL:
      if (value == null) {
        unsetInstall();
      } else {
        setInstall((List<Long>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ID:
      return getId();

    case NAME:
      return getName();

    case COMMON:
      return isCommon();

    case ROOT:
      return isRoot();

    case BRAND_ID:
      return getBrand_id();

    case MODEL_ID:
      return getModel_id();

    case VERSION_ID:
      return getVersion_id();

    case BASE_VERSION_ID:
      return getBase_version_id();

    case PACKAGE_ID:
      return getPackage_id();

    case PRE:
      return getPre();

    case INSTALL:
      return getInstall();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ID:
      return isSetId();
    case NAME:
      return isSetName();
    case COMMON:
      return isSetCommon();
    case ROOT:
      return isSetRoot();
    case BRAND_ID:
      return isSetBrand_id();
    case MODEL_ID:
      return isSetModel_id();
    case VERSION_ID:
      return isSetVersion_id();
    case BASE_VERSION_ID:
      return isSetBase_version_id();
    case PACKAGE_ID:
      return isSetPackage_id();
    case PRE:
      return isSetPre();
    case INSTALL:
      return isSetInstall();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof AppPackageStruct)
      return this.equals((AppPackageStruct)that);
    return false;
  }

  public boolean equals(AppPackageStruct that) {
    if (that == null)
      return false;

    boolean this_present_id = true;
    boolean that_present_id = true;
    if (this_present_id || that_present_id) {
      if (!(this_present_id && that_present_id))
        return false;
      if (this.id != that.id)
        return false;
    }

    boolean this_present_name = true && this.isSetName();
    boolean that_present_name = true && that.isSetName();
    if (this_present_name || that_present_name) {
      if (!(this_present_name && that_present_name))
        return false;
      if (!this.name.equals(that.name))
        return false;
    }

    boolean this_present_common = true;
    boolean that_present_common = true;
    if (this_present_common || that_present_common) {
      if (!(this_present_common && that_present_common))
        return false;
      if (this.common != that.common)
        return false;
    }

    boolean this_present_root = true;
    boolean that_present_root = true;
    if (this_present_root || that_present_root) {
      if (!(this_present_root && that_present_root))
        return false;
      if (this.root != that.root)
        return false;
    }

    boolean this_present_brand_id = true && this.isSetBrand_id();
    boolean that_present_brand_id = true && that.isSetBrand_id();
    if (this_present_brand_id || that_present_brand_id) {
      if (!(this_present_brand_id && that_present_brand_id))
        return false;
      if (this.brand_id != that.brand_id)
        return false;
    }

    boolean this_present_model_id = true && this.isSetModel_id();
    boolean that_present_model_id = true && that.isSetModel_id();
    if (this_present_model_id || that_present_model_id) {
      if (!(this_present_model_id && that_present_model_id))
        return false;
      if (this.model_id != that.model_id)
        return false;
    }

    boolean this_present_version_id = true && this.isSetVersion_id();
    boolean that_present_version_id = true && that.isSetVersion_id();
    if (this_present_version_id || that_present_version_id) {
      if (!(this_present_version_id && that_present_version_id))
        return false;
      if (this.version_id != that.version_id)
        return false;
    }

    boolean this_present_base_version_id = true && this.isSetBase_version_id();
    boolean that_present_base_version_id = true && that.isSetBase_version_id();
    if (this_present_base_version_id || that_present_base_version_id) {
      if (!(this_present_base_version_id && that_present_base_version_id))
        return false;
      if (this.base_version_id != that.base_version_id)
        return false;
    }

    boolean this_present_package_id = true;
    boolean that_present_package_id = true;
    if (this_present_package_id || that_present_package_id) {
      if (!(this_present_package_id && that_present_package_id))
        return false;
      if (this.package_id != that.package_id)
        return false;
    }

    boolean this_present_pre = true && this.isSetPre();
    boolean that_present_pre = true && that.isSetPre();
    if (this_present_pre || that_present_pre) {
      if (!(this_present_pre && that_present_pre))
        return false;
      if (!this.pre.equals(that.pre))
        return false;
    }

    boolean this_present_install = true && this.isSetInstall();
    boolean that_present_install = true && that.isSetInstall();
    if (this_present_install || that_present_install) {
      if (!(this_present_install && that_present_install))
        return false;
      if (!this.install.equals(that.install))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_id = true;
    list.add(present_id);
    if (present_id)
      list.add(id);

    boolean present_name = true && (isSetName());
    list.add(present_name);
    if (present_name)
      list.add(name);

    boolean present_common = true;
    list.add(present_common);
    if (present_common)
      list.add(common);

    boolean present_root = true;
    list.add(present_root);
    if (present_root)
      list.add(root);

    boolean present_brand_id = true && (isSetBrand_id());
    list.add(present_brand_id);
    if (present_brand_id)
      list.add(brand_id);

    boolean present_model_id = true && (isSetModel_id());
    list.add(present_model_id);
    if (present_model_id)
      list.add(model_id);

    boolean present_version_id = true && (isSetVersion_id());
    list.add(present_version_id);
    if (present_version_id)
      list.add(version_id);

    boolean present_base_version_id = true && (isSetBase_version_id());
    list.add(present_base_version_id);
    if (present_base_version_id)
      list.add(base_version_id);

    boolean present_package_id = true;
    list.add(present_package_id);
    if (present_package_id)
      list.add(package_id);

    boolean present_pre = true && (isSetPre());
    list.add(present_pre);
    if (present_pre)
      list.add(pre);

    boolean present_install = true && (isSetInstall());
    list.add(present_install);
    if (present_install)
      list.add(install);

    return list.hashCode();
  }

  @Override
  public int compareTo(AppPackageStruct other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetId()).compareTo(other.isSetId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.id, other.id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetName()).compareTo(other.isSetName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.name, other.name);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCommon()).compareTo(other.isSetCommon());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCommon()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.common, other.common);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetRoot()).compareTo(other.isSetRoot());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRoot()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.root, other.root);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetBrand_id()).compareTo(other.isSetBrand_id());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBrand_id()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.brand_id, other.brand_id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetModel_id()).compareTo(other.isSetModel_id());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetModel_id()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.model_id, other.model_id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetVersion_id()).compareTo(other.isSetVersion_id());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetVersion_id()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.version_id, other.version_id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetBase_version_id()).compareTo(other.isSetBase_version_id());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBase_version_id()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.base_version_id, other.base_version_id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPackage_id()).compareTo(other.isSetPackage_id());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPackage_id()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.package_id, other.package_id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPre()).compareTo(other.isSetPre());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPre()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.pre, other.pre);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetInstall()).compareTo(other.isSetInstall());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetInstall()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.install, other.install);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("AppPackageStruct(");
    boolean first = true;

    sb.append("id:");
    sb.append(this.id);
    first = false;
    if (!first) sb.append(", ");
    sb.append("name:");
    if (this.name == null) {
      sb.append("null");
    } else {
      sb.append(this.name);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("common:");
    sb.append(this.common);
    first = false;
    if (!first) sb.append(", ");
    sb.append("root:");
    sb.append(this.root);
    first = false;
    if (isSetBrand_id()) {
      if (!first) sb.append(", ");
      sb.append("brand_id:");
      sb.append(this.brand_id);
      first = false;
    }
    if (isSetModel_id()) {
      if (!first) sb.append(", ");
      sb.append("model_id:");
      sb.append(this.model_id);
      first = false;
    }
    if (isSetVersion_id()) {
      if (!first) sb.append(", ");
      sb.append("version_id:");
      sb.append(this.version_id);
      first = false;
    }
    if (isSetBase_version_id()) {
      if (!first) sb.append(", ");
      sb.append("base_version_id:");
      sb.append(this.base_version_id);
      first = false;
    }
    if (!first) sb.append(", ");
    sb.append("package_id:");
    sb.append(this.package_id);
    first = false;
    if (isSetPre()) {
      if (!first) sb.append(", ");
      sb.append("pre:");
      if (this.pre == null) {
        sb.append("null");
      } else {
        sb.append(this.pre);
      }
      first = false;
    }
    if (isSetInstall()) {
      if (!first) sb.append(", ");
      sb.append("install:");
      if (this.install == null) {
        sb.append("null");
      } else {
        sb.append(this.install);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class AppPackageStructStandardSchemeFactory implements SchemeFactory {
    public AppPackageStructStandardScheme getScheme() {
      return new AppPackageStructStandardScheme();
    }
  }

  private static class AppPackageStructStandardScheme extends StandardScheme<AppPackageStruct> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, AppPackageStruct struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.id = iprot.readI64();
              struct.setIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.name = iprot.readString();
              struct.setNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // COMMON
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.common = iprot.readBool();
              struct.setCommonIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // ROOT
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.root = iprot.readBool();
              struct.setRootIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // BRAND_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.brand_id = iprot.readI64();
              struct.setBrand_idIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // MODEL_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.model_id = iprot.readI64();
              struct.setModel_idIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // VERSION_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.version_id = iprot.readI64();
              struct.setVersion_idIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // BASE_VERSION_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.base_version_id = iprot.readI64();
              struct.setBase_version_idIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // PACKAGE_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.package_id = iprot.readI64();
              struct.setPackage_idIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // PRE
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list20 = iprot.readListBegin();
                struct.pre = new ArrayList<Long>(_list20.size);
                long _elem21;
                for (int _i22 = 0; _i22 < _list20.size; ++_i22)
                {
                  _elem21 = iprot.readI64();
                  struct.pre.add(_elem21);
                }
                iprot.readListEnd();
              }
              struct.setPreIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 11: // INSTALL
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list23 = iprot.readListBegin();
                struct.install = new ArrayList<Long>(_list23.size);
                long _elem24;
                for (int _i25 = 0; _i25 < _list23.size; ++_i25)
                {
                  _elem24 = iprot.readI64();
                  struct.install.add(_elem24);
                }
                iprot.readListEnd();
              }
              struct.setInstallIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, AppPackageStruct struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(ID_FIELD_DESC);
      oprot.writeI64(struct.id);
      oprot.writeFieldEnd();
      if (struct.name != null) {
        oprot.writeFieldBegin(NAME_FIELD_DESC);
        oprot.writeString(struct.name);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(COMMON_FIELD_DESC);
      oprot.writeBool(struct.common);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(ROOT_FIELD_DESC);
      oprot.writeBool(struct.root);
      oprot.writeFieldEnd();
      if (struct.isSetBrand_id()) {
        oprot.writeFieldBegin(BRAND_ID_FIELD_DESC);
        oprot.writeI64(struct.brand_id);
        oprot.writeFieldEnd();
      }
      if (struct.isSetModel_id()) {
        oprot.writeFieldBegin(MODEL_ID_FIELD_DESC);
        oprot.writeI64(struct.model_id);
        oprot.writeFieldEnd();
      }
      if (struct.isSetVersion_id()) {
        oprot.writeFieldBegin(VERSION_ID_FIELD_DESC);
        oprot.writeI64(struct.version_id);
        oprot.writeFieldEnd();
      }
      if (struct.isSetBase_version_id()) {
        oprot.writeFieldBegin(BASE_VERSION_ID_FIELD_DESC);
        oprot.writeI64(struct.base_version_id);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(PACKAGE_ID_FIELD_DESC);
      oprot.writeI64(struct.package_id);
      oprot.writeFieldEnd();
      if (struct.pre != null) {
        if (struct.isSetPre()) {
          oprot.writeFieldBegin(PRE_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I64, struct.pre.size()));
            for (long _iter26 : struct.pre)
            {
              oprot.writeI64(_iter26);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.install != null) {
        if (struct.isSetInstall()) {
          oprot.writeFieldBegin(INSTALL_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I64, struct.install.size()));
            for (long _iter27 : struct.install)
            {
              oprot.writeI64(_iter27);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class AppPackageStructTupleSchemeFactory implements SchemeFactory {
    public AppPackageStructTupleScheme getScheme() {
      return new AppPackageStructTupleScheme();
    }
  }

  private static class AppPackageStructTupleScheme extends TupleScheme<AppPackageStruct> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, AppPackageStruct struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetId()) {
        optionals.set(0);
      }
      if (struct.isSetName()) {
        optionals.set(1);
      }
      if (struct.isSetCommon()) {
        optionals.set(2);
      }
      if (struct.isSetRoot()) {
        optionals.set(3);
      }
      if (struct.isSetBrand_id()) {
        optionals.set(4);
      }
      if (struct.isSetModel_id()) {
        optionals.set(5);
      }
      if (struct.isSetVersion_id()) {
        optionals.set(6);
      }
      if (struct.isSetBase_version_id()) {
        optionals.set(7);
      }
      if (struct.isSetPackage_id()) {
        optionals.set(8);
      }
      if (struct.isSetPre()) {
        optionals.set(9);
      }
      if (struct.isSetInstall()) {
        optionals.set(10);
      }
      oprot.writeBitSet(optionals, 11);
      if (struct.isSetId()) {
        oprot.writeI64(struct.id);
      }
      if (struct.isSetName()) {
        oprot.writeString(struct.name);
      }
      if (struct.isSetCommon()) {
        oprot.writeBool(struct.common);
      }
      if (struct.isSetRoot()) {
        oprot.writeBool(struct.root);
      }
      if (struct.isSetBrand_id()) {
        oprot.writeI64(struct.brand_id);
      }
      if (struct.isSetModel_id()) {
        oprot.writeI64(struct.model_id);
      }
      if (struct.isSetVersion_id()) {
        oprot.writeI64(struct.version_id);
      }
      if (struct.isSetBase_version_id()) {
        oprot.writeI64(struct.base_version_id);
      }
      if (struct.isSetPackage_id()) {
        oprot.writeI64(struct.package_id);
      }
      if (struct.isSetPre()) {
        {
          oprot.writeI32(struct.pre.size());
          for (long _iter28 : struct.pre)
          {
            oprot.writeI64(_iter28);
          }
        }
      }
      if (struct.isSetInstall()) {
        {
          oprot.writeI32(struct.install.size());
          for (long _iter29 : struct.install)
          {
            oprot.writeI64(_iter29);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, AppPackageStruct struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(11);
      if (incoming.get(0)) {
        struct.id = iprot.readI64();
        struct.setIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.name = iprot.readString();
        struct.setNameIsSet(true);
      }
      if (incoming.get(2)) {
        struct.common = iprot.readBool();
        struct.setCommonIsSet(true);
      }
      if (incoming.get(3)) {
        struct.root = iprot.readBool();
        struct.setRootIsSet(true);
      }
      if (incoming.get(4)) {
        struct.brand_id = iprot.readI64();
        struct.setBrand_idIsSet(true);
      }
      if (incoming.get(5)) {
        struct.model_id = iprot.readI64();
        struct.setModel_idIsSet(true);
      }
      if (incoming.get(6)) {
        struct.version_id = iprot.readI64();
        struct.setVersion_idIsSet(true);
      }
      if (incoming.get(7)) {
        struct.base_version_id = iprot.readI64();
        struct.setBase_version_idIsSet(true);
      }
      if (incoming.get(8)) {
        struct.package_id = iprot.readI64();
        struct.setPackage_idIsSet(true);
      }
      if (incoming.get(9)) {
        {
          org.apache.thrift.protocol.TList _list30 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I64, iprot.readI32());
          struct.pre = new ArrayList<Long>(_list30.size);
          long _elem31;
          for (int _i32 = 0; _i32 < _list30.size; ++_i32)
          {
            _elem31 = iprot.readI64();
            struct.pre.add(_elem31);
          }
        }
        struct.setPreIsSet(true);
      }
      if (incoming.get(10)) {
        {
          org.apache.thrift.protocol.TList _list33 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I64, iprot.readI32());
          struct.install = new ArrayList<Long>(_list33.size);
          long _elem34;
          for (int _i35 = 0; _i35 < _list33.size; ++_i35)
          {
            _elem34 = iprot.readI64();
            struct.install.add(_elem34);
          }
        }
        struct.setInstallIsSet(true);
      }
    }
  }

}

